auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
    docker.io/library/python:3.11.3-slim: registry.cn-hangzhou.aliyuncs.com/liangjw/python:3.11.3-slim
